[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[dependencies]
domain = { path = "../domain" }
diesel = "2.1"
log = "0.4.20"
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.70"

chrono = "0.4.31"
