version: '3.9'

# services:
#   zibelina-store-api:
#     container_name: zibelina-store-api
#     build: 
#       context: .
#       dockerfile: ./server/Dockerfile
#       args: 
#         DATABASE_URL: postgres://user:password@localhost/zibelina
#     ports:
#       - '8000:8000'
#     depends_on:
#       - zibelina-store-pg

#   zibelina-store-pg:
#     container_name: zibelina-store-pg
#     image: postgres:16.1
#     environment:
#       POSTGRES_USER: user
#       POSTGRES_PASSWORD: password
#       POSTGRES_DB: zibelina
#     ports:
#       - '5432:5432'
#     volumes:
#       - ./postgres-data:/var/lib/postgresql/data
#     restart: unless-stopped

# volumes:
#   postgres-data:

services:
  postgres:
    container_name: zibelina-store-pg
    image: postgres:16.1
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: zibelina
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data:
